version: '3.8'
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.1
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    volumes:
      - /Users/jerry/LLM/weaviate/data/:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 50
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: text2vec-ollama
      ENABLE_MODULES: text2vec-ollama
      CLUSTER_HOSTNAME: 'node1'
      GRPC_ENABLED: 'true'
      GRPC_ENABLE_REFLECTION: 'true'
      GRPC_PORT: 50051
